### PR TITLE
Refactor container app resources

### PR DESCRIPTION
**Pull request by Stretch96**
* The `azurerm_container_app` and `azurerm_container_app_environment` resources are now avaible from the provider.
* This refactors the azapi resources, to use the real resources instead.
* Note: This will destroy and recreate the resources, so we'll be better off removing/importing the remote Azure resources.

### CODE REVIEW

**Comment by DrizzlyOwl** [comment]
https://github.com/hashicorp/terraform-provider-azurerm/issues/20435

**Comment by DrizzlyOwl** [comment]
Just needs Custom Container Apps testing :) Paging @ryantk if you have the time to refactor ;)

**Comment by DrizzlyOwl** [comment]
Ran into this error after deleting a Container app secret env var.
```
│ Error: cannot remove secrets from Container Apps at this time due to a limitation in the Container Apps Service. Please see `https://github.com/microsoft/azure-container-apps/issues/395` for more details
```

https://github.com/microsoft/azure-container-apps/issues/395

**Comment by DrizzlyOwl** [comment]
Thanks for updating @Stretch96.

I'd like to see https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/pull/245 refactored into this PR too
Additionally, can we add some extra outputs for the container app and CDN FQDNs so that folks can use those as references elsewhere?

**Comment by Stretch96** [comment]
https://github.com/hashicorp/terraform-provider-azurerm/issues/20535

**Comment by DrizzlyOwl** [comment]
🚢

**Review by DrizzlyOwl — APPROVED** [review]

**Pull request merged**
